### ISSUE TITLE
初回描画時にフォントが適用されない

### ISSUE THREAD

**Issue by inaniwaudon** [inaniwaudon/genkotsu#6]
Twitter 上での指摘：
https://twitter.com/_yuheiy/status/1653379972927717377

Web フォントのロードを待ってから Canvas の描画をすると良い

**Comment by eggplants** [comment]
うーん開発環境では解決しているようですが、
<https://inaniwaudon.github.io/genkotsu/> を見ると依然として初回読み込み時フォントが適用されてないです。

`yarn build && yarn start --port 3001` で立ち上がった環境でも同様の状況になります。(確認不足でした、すみません‥)

**Comment by inaniwaudon** [comment]
確認しました、確かにそうですね……
https://github.com/typekit/webfontloader あたりを使って解決するのが無難そうです。

**Comment by inaniwaudon** [comment]
（今度こそ）正しく描画されていそうです。ありがとうございます。
